name: SBFlavor
favicon: null
layout_spectrum: 0.9780995580367744
typography_spectrum: 0.06628361460752785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09773769066669047
  lightness: 0.1360019186977297
  saturation: 0.13549859425984323
  rhythmicContrast: 0.06720301019959152
purpose: []
